Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days

MySQL:
  Host: sql.freedb.tech
  Port: 3306
  Username: freedb_quocthinh
  Password: g$%m%7eCZmBxs!J
  DBName: freedb_nettruyen
  DriverName: mysql

Redis:
  Addr: red-cnq0g1v109ks73eca4l0:6379
  Username:
  Password:
  DB: 0
  PoolSize: 300
  PoolTimeout: 240

Dropbox:
  AppKey: 22fbmanjs9dvpqs
  AppSecret: gy41e9xmgjpk9k4
  RefreshToken: acUDBMzDdCkAAAAAAAAAAZFUJhpo2VYMfdxefDZ0qVGvnENZEJC5um8NFkHSLEuV

CorsPolicy:
  AllowOrigins:
    - "*"
  AllowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  AllowHeaders:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "Content-Length"
    - "Origin"
  ExposeHeaders:
    - "Content-Length"
  AllowCredentials: true
  MaxAge: 43200 # 12 hours