Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days
  ResetPasswordCodeExpiration: 180 # 3 minutes

MySQL:
  Host: monorail.proxy.rlwy.net
  Port: 15777
  Username: root
  Password: DffsQNMJZLWeOajTmuhFClsWkjozbKKh
  DBName: nettruyen
  DriverName: mysql

Redis:
  Addr: red-cnq0g1v109ks73eca4l0:6379
  Username:
  Password:
  DB: 0
  PoolSize: 300
  PoolTimeout: 240

Dropbox:
  AppKey: 22fbmanjs9dvpqs
  AppSecret: gy41e9xmgjpk9k4
  RefreshToken: acUDBMzDdCkAAAAAAAAAAZFUJhpo2VYMfdxefDZ0qVGvnENZEJC5um8NFkHSLEuV

Gmail:
  "ClientId": "153351185108-o2061k0308r7g628i2he0m7m1e488nuu.apps.googleusercontent.com"
  "ClientSecret": "Ilt1i7jas4EIpvSxKcMFWvIt"
  "RefreshToken": "1//041gvkYW1NY7UCgYIARAAGAQSNwF-L9IrURFJ5bVuc889Cki6ztOVFhSfU7MDXPnbl9NtWIcpgoattD3hISzF-zgByo7yA3aso1A"

CorsPolicy:
  AllowOrigins:
    - "*"
  AllowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  AllowHeaders:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "Content-Length"
    - "Origin"
  ExposeHeaders:
    - "Content-Length"
  AllowCredentials: true
  MaxAge: 43200 # 12 hours
