Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days

MySQL:
  Host: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
  Port: 4000
  Username: 48mM87i9c6HEevz.root
  Password: 1Q2vDXNntnesph64
  DBName: nettruyen
  DriverName: mysql

Redis:
  Addr: red-cnq0g1v109ks73eca4l0:6379
  Username:
  Password:
  DB: 0
  PoolSize: 300
  PoolTimeout: 240

Dropbox:
  AppKey: 22fbmanjs9dvpqs
  AppSecret: gy41e9xmgjpk9k4
  RefreshToken: acUDBMzDdCkAAAAAAAAAAZFUJhpo2VYMfdxefDZ0qVGvnENZEJC5um8NFkHSLEuV