Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days
  ResetPasswordCodeExpiration: 300 # 3 minutes

MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password:
  DBName: nettruyen
  DriverName: mysql

Redis:
  Addr: localhost:6379
  Username:
  Password:
  DB: 0
  PoolSize: 300
  PoolTimeout: 240

Dropbox:
  AppKey: appkey
  AppSecret: appsecret
  RefreshToken: refreshtoken

Gmail:
  "ClientId": "Your ClientId"
  "ClientSecret": "Your ClientSecret"
  "RefreshToken": "Your RefreshToken"

CorsPolicy:
  AllowOrigins:
    - "*"
  AllowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  AllowHeaders:
    - "Accept"
    - "Authorization"
    - "Content-Typed"
    - "Content-Length"
    - "Origin"
  ExposeHeaders:
    - "Content-Length"
  AllowCredentials: true
  MaxAge: 43200 # 12 hours