Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days

MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: 
  DBName: nettruyen
  DriverName: mysql

Redis:
  Addr: localhost:6379
  Username:
  Password:
  DB: 0
  PoolSize: 300
  PoolTimeout: 240