Server:
  Port: :8080
  ReadTimeout: 5
  WriteTimeout: 5
  JwtSecretKey: B5bJHoI8aVLjAAeV
  JwtUserExpiration: 604800 # 7 days

MySQL:
#  Host: bnjsdjmyfiuggbvdrwqd-mysql.services.clever-cloud.com
#  Port: 3306
#  Username: uqlzhbyuhhtr7nhp
#  Password: Xe7mnphtx0o4DBXhn8l3
#  DBName: bnjsdjmyfiuggbvdrwqd
#  DriverName: mysql
  Host: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
  Port: 4000
  Username: 48mM87i9c6HEevz.root
  Password: 1Q2vDXNntnesph64
  DBName: nettruyen
  DriverName: mysql

  Redis:
    Addr: singapore-redis.render.com:6379
    Username: red-cnq0g1v109ks73eca4l0
    Password: gL0kKXmORbs5jmFcdndpSH0mLJo1Zj6j
    DB: 0
    PoolSize: 300
    PoolTimeout: 240